uav1:
  home:
    x: 8
    y: 4
    z: 1.4

uav2:
  home:
    x: 8
    y: 6
    z: 1.4

height: 3

corners:
  p1:
    x: 7
    y: 2
  p2:
    x: 7 
    y: 8
  p3:
    x: 2
    y: 8
  p4:
    x: 2
    y: 2

segment_size: 1

margin: 1